# Generated by Django 3.2.4 on 2021-06-06 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_alter_compiler_langauge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compiler',
            old_name='langauge',
            new_name='language',
        ),
    ]
