# Generated by Django 3.2.4 on 2021-06-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('uName', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
