# Generated by Django 3.2.4 on 2021-06-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uName',
            new_name='userName',
        ),
    ]
