# Generated by Django 3.2.4 on 2021-06-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.CharField(max_length=10)),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=10)),
                ('customInput', models.TextField()),
                ('expectedOuput', models.TextField()),
                ('output', models.TextField()),
                ('verdict', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
