# Generated by Django 3.2.4 on 2021-06-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiler',
            name='customInput',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='expectedOuput',
            field=models.TextField(blank=True),
        ),
    ]
