# Generated by Django 3.2.4 on 2021-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Compiler', '0002_auto_20210620_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiler',
            name='output',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='compiler',
            name='verdict',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
