# Generated by Django 3.2.4 on 2021-06-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_rename_langauge_compiler_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiler',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
