# Generated by Django 3.2.4 on 2021-06-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0005_compiler_questioninput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiler',
            name='questionInput',
            field=models.TextField(blank=True, null=True),
        ),
    ]
